# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x07scoring\"\xbf\x01\n\x0ePredictRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x13\n\x0btemp_madrid\x18\x02 \x01(\x01\x12\x16\n\x0etemp_barcelona\x18\x03 \x01(\x01\x12\x15\n\rtemp_valencia\x18\x04 \x01(\x01\x12\x14\n\x0ctemp_seville\x18\x05 \x01(\x01\x12\x13\n\x0btemp_bilbao\x18\x06 \x01(\x01\x12\x14\n\x0cload_24h_ago\x18\x07 \x01(\x01\x12\x15\n\rload_168h_ago\x18\x08 \x01(\x01\"C\n\x0fPredictResponse\x12\x19\n\x11predicted_load_mw\x18\x01 \x01(\x01\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"@\n\x13\x42\x61tchPredictRequest\x12)\n\x08requests\x18\x01 \x03(\x0b\x32\x17.scoring.PredictRequest2\x91\x01\n\x07Scoring\x12<\n\x07Predict\x12\x17.scoring.PredictRequest\x1a\x18.scoring.PredictResponse\x12H\n\x0cPredictBatch\x12\x1c.scoring.BatchPredictRequest\x1a\x18.scoring.PredictResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=27
  _globals['_PREDICTREQUEST']._serialized_end=218
  _globals['_PREDICTRESPONSE']._serialized_start=220
  _globals['_PREDICTRESPONSE']._serialized_end=287
  _globals['_BATCHPREDICTREQUEST']._serialized_start=289
  _globals['_BATCHPREDICTREQUEST']._serialized_end=353
  _globals['_SCORING']._serialized_start=356
  _globals['_SCORING']._serialized_end=501
# @@protoc_insertion_point(module_scope)
